In [5]:
#RuiMing Li 
#Lab 3 

#Import libraries
import numpy as np #np is the widely adopted alias for numpy

#Read the contents of a file
file_name = 'exam_grades.csv' #the filename
fh = open(file_name, mode='r') #r means read the file
data = fh.read() #start reading the contents of the file
fh.close() #close the connection to the file

print(data)
print(type(data))

year,exam1,exam2,exam3,course_grade
2000,84.5,69.5,86.5,76.2564
2000,80,74,67,75.3882
2000,56,70,71.5,67.0564
2000,64,61,67.5,63.4538
2000,90.5,72.5,75,72.3949
2000,74,78.5,84.5,71.4128
2000,60.5,44,58,56.0949
2000,89,82,88,78.0103
2000,87.5,86.5,95,82.9026
2000,91,98,88,89.0846
2000,79.5,88,56,72.9769
2000,96,91.5,78,82.5282
2000,55,79.5,72,69.9872
2000,80,83.5,70,67.7256
2000,64.5,83.5,77,80.3051
2000,73,90,96,74.8744
2000,83,79,65,71.1615
2000,72,91,90,76.5615
2000,57.9,53,47,56.9903
2000,89,83.5,78.5,80.8026
2000,69,57,88,69.4308
2000,91,91,95.5,92.0051
2000,68,84.5,64,67.9051
2000,83,89.5,93,79.7872
2000,72,77.5,67,67.1256
2000,56,45,61,58.6308
2000,55,71,72,67.8308
2000,68.5,64,93,77.6903
2000,68.5,79.5,50.5,69.9308
2000,70,71,76,69.6769
2000,75,81,81.5,68.0923
2000,68.5,66,58,60.3128
2000,54,84,88,72.3821
2000,79.6,67,72,67.4787
2000,85,61,44.5,66.2364
2000,82,86.5,92.5,83.3231
2000,65,83.5,87,77.6436
2000,76,50,91.5,70.9462
2000,94.5,67,96,86.0133
2000,72,67,90,72.0269
2000,65.

In [6]:
grades = np.loadtxt('exam_grades.csv', #the file name
                  delimiter=',', #indicate the delimiter
                  skiprows=1) #skip the header

#verify the data was imported correctly
print(grades[:5,]) #show the first five rows of the data


[[2000.       84.5      69.5      86.5      76.2564]
 [2000.       80.       74.       67.       75.3882]
 [2000.       56.       70.       71.5      67.0564]
 [2000.       64.       61.       67.5      63.4538]
 [2000.       90.5      72.5      75.       72.3949]]


In [22]:
print("The total number of columns is: ", grades.shape[0])
print("The total number of observations is: ", grades.shape[1])

course_grades = grades[0:233, 4]
print(course_grades[:5,]) #show the first five rows of the data

print('The maximum value is: ', course_grades.max())
print('The minimum value is: ', course_grades.min())


The total number of columns is:  233
The total number of observations is:  5
[76.2564 75.3882 67.0564 63.4538 72.3949]
The maximum value is:  97.5667
The minimum value is:  43.2733


In [26]:
course_years = grades[0:233, 0]
print(course_years)
no_duplicate = list()

[2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000.
 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000.
 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000.
 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000.
 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000.
 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000.
 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000. 2000.
 2000. 2000. 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001.
 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001.
 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001.
 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001.
 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001.
 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001. 2001.
 2001. 2001. 2001. 2001. 2001. 2002. 2002. 2002. 20

In [27]:
#filter the array to no duplicates 
for x in course_years:
    if x not in no_duplicate:
        no_duplicate.append(x)
print(no_duplicate)

[2000.0, 2001.0, 2002.0, 2003.0]


In [34]:
#count number of students in each year 
num_2000 = 0; 
num_2001 = 0; 
num_2002 = 0; 
num_2003 = 0; 
for x in course_years: 
    if x == 2000: 
        num_2000 += 1 
    elif x == 2001:
        num_2001 += 1 
    elif x == 2002: 
        num_2002 += 1
    elif x == 2003:
        num_2003 += 1

print("The number of students in 2000: ", num_2000)
print("The number of students in 2001: ", num_2001)
print("The number of students in 2002: ", num_2002)
print("The number of students in 2003: ", num_2003)


The number of students in 2000:  86
The number of students in 2001:  75
The number of students in 2002:  36
The number of students in 2003:  36


In [58]:
exam1_2000 = []; 
exam2_2000 = list(); 
exam3_2000 = list(); 

exam1_2001 = list(); 
exam2_2001 = list(); 
exam3_2001 = list(); 


exam1_2002 = list(); 
exam2_2002 = list(); 
exam3_2002 = list(); 

exam1_2003 = list(); 
exam2_2003 = list(); 
exam3_2003 = list(); 

for x in range(233): 
    if grades[x, 0] == 2000:
        exam1_2000.append(grades[x, 1])
        exam2_2000.append(grades[x, 2])
        exam3_2000.append(grades[x, 3])
        
    if grades[x, 0] == 2001:
        exam1_2001.append(grades[x, 1])
        exam2_2001.append(grades[x, 2])
        exam3_2001.append(grades[x, 3])
    
    if grades[x, 0] == 2002:
        exam1_2002.append(grades[x, 1])
        exam2_2002.append(grades[x, 2])
        exam3_2002.append(grades[x, 3])
        
    if grades[x, 0] == 2003:
        exam1_2003.append(grades[x, 1])
        exam2_2003.append(grades[x, 2])
        exam3_2003.append(grades[x, 3])

print("The maximum score for 2000 exam 1 is:", max(exam1_2000))
print("The minimum score for 2000 exam 1 is:", min(exam1_2000))
print("The average score for 2000 exam 1 is:", np.mean(exam1_2000))
print("The standard deviation for 2000 exam 1 is:", np.std(exam1_2000))

print("The maximum score for 2000 exam 2 is:", max(exam2_2000))
print("The minimum score for 2000 exam 2 is:", min(exam2_2000))
print("The average score for 2000 exam 2 is:", np.mean(exam2_2000))
print("The standard deviation for 2001 exam 2 is:", np.std(exam2_2000))

print("The maximum score for 2000 exam 3 is:", max(exam3_2000))
print("The minimum score for 2000 exam 3 is:", min(exam3_2000))
print("The average score for 2000 exam 3 is:", np.mean(exam3_2000))
print("The standard deviation for 2001 exam 3 is:", np.std(exam3_2000))

print("\n") 

print("The maximum score for 2001 exam 1 is:", max(exam1_2001))
print("The minimum score for 2001 exam 1 is:", min(exam1_2001))
print("The average score for 2001 exam 1 is:", np.mean(exam1_2001))
print("The standard deviation for 2001 exam 1 is:", np.std(exam1_2001))

print("The maximum score for 2001 exam 2 is:", max(exam2_2001))
print("The minimum score for 2001 exam 2 is:", min(exam2_2001))
print("The average score for 2001 exam 2 is:", np.mean(exam2_2001))
print("The standard deviation for 2001 exam 2 is:", np.std(exam2_2001))

print("The maximum score for 2001 exam 3 is:", max(exam3_2001))
print("The minimum score for 2001 exam 3 is:", min(exam3_2001))
print("The average score for 2001 exam 3 is:", np.mean(exam3_2001))
print("The standard deviation for 2001 exam 3 is:", np.std(exam3_2001))

print("\n") 

print("The maximum score for 2002 exam 1 is:", max(exam1_2002))
print("The minimum score for 2002 exam 1 is:", min(exam1_2002))
print("The average score for 2002 exam 1 is:", np.mean(exam1_2002))
print("The standard deviation for 2002 exam 1 is:", np.std(exam1_2002))

print("The maximum score for 2002 exam 2 is:", max(exam2_2002))
print("The minimum score for 2002 exam 2 is:", min(exam2_2002))
print("The average score for 2002 exam 2 is:", np.mean(exam2_2002))
print("The standard deviation for 2002 exam 2 is:", np.std(exam2_2002))

print("The maximum score for 2002 exam 3 is:", max(exam3_2002))
print("The minimum score for 2002 exam 3 is:", min(exam3_2002))
print("The average score for 2002 exam 3 is:", np.mean(exam3_2002))
print("The standard deviation for 2002 exam 3 is:", np.std(exam3_2002))

print("\n") 



print("The maximum score for 2003 exam 1 is:", max(exam1_2003))
print("The minimum score for 2003 exam 1 is:", min(exam1_2003))
print("The average score for 2003 exam 1 is:", np.mean(exam1_2003))
print("The standard deviation for 2003 exam 1 is:", np.std(exam1_2003))

print("The maximum score for 2003 exam 2 is:", max(exam2_2003))
print("The minimum score for 2003 exam 2 is:", min(exam2_2003))
print("The average score for 2003 exam 2 is:", np.mean(exam2_2003))
print("The standard deviation for 2003 exam 2 is:", np.std(exam2_2003))

print("The maximum score for 2003 exam 3 is:", max(exam3_2003))
print("The minimum score for 2003 exam 3 is:", min(exam3_2003))
print("The average score for 2003 exam 3 is:", np.mean(exam3_2003))
print("The standard deviation for 2003 exam 3 is:", np.std(exam3_2003))

# # The average for the 2000 exams were roughly the same and stayed around 74. The average for the 2001 exams had a 
# # little difference where the average for exam 1 was higher than the average for exams 2 and 3. The average for the 
# 2002 exams were similar to the 2001 exams where exam 3 was higher than the average for exams 1 and 2. The average for
# the 2003 exams differ drastically where the lowest was a 67 for exam 2 and the highest average was a 83 for exam 1

The maximum score for 2000 exam 1 is: 96.0
The minimum score for 2000 exam 1 is: 46.5
The average score for 2000 exam 1 is: 74.48572906976743
The standard deviation for 2000 exam 1 is: 11.394237808614985
The maximum score for 2000 exam 2 is: 99.5
The minimum score for 2000 exam 2 is: 41.0
The average score for 2000 exam 2 is: 74.18604651162791
The standard deviation for 2001 exam 2 is: 13.023915058065189
The maximum score for 2000 exam 3 is: 97.0
The minimum score for 2000 exam 3 is: 28.0
The average score for 2000 exam 3 is: 73.23255813953489
The standard deviation for 2001 exam 3 is: 15.704128044624722


The maximum score for 2001 exam 1 is: 98.0
The minimum score for 2001 exam 1 is: 58.0
The average score for 2001 exam 1 is: 85.00566666666667
The standard deviation for 2001 exam 1 is: 8.365881676322122
The maximum score for 2001 exam 2 is: 96.5
The minimum score for 2001 exam 2 is: 41.5
The average score for 2001 exam 2 is: 71.36133333333332
The standard deviation for 2001 exam 2 is

In [61]:
# Numpy arrays can only store elements of the same type 
list = [1, 4, 7, "a"]
print(list) 

numpy_array = np.array([1, 4, 7, "a"])
print(numpy_array)

#you can see from the print results that numpy_array was converted to strings 

[1, 4, 7, 'a']
['1' '4' '7' 'a']
